apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"  #指定到一个存在的service的名字
  replicas: 2
  selector:
    matchLabels:
      app: nginx  #必须匹配 .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: nginx  # 必须配置 .spec.selector.matchLabels
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
            name: web
